#!/bin/bash
rm submissions/*.txt
rm submissions/*.png
rm submissions/*.chk
rm submissions/*.cathbls
rm submissions/*.pdbbls
rm submissions/*.pdb
rm submissions/*.nndiso
rm submissions/*.mtx
rm submissions/*.ss
rm submissions/*.ss2
rm submissions/*.psicov
rm submissions/*.solv
rm submissions/*.coils
rm submissions/*.horiz
rm submissions/*.comb
rm submissions/*.dnb
rm submissions/*.diso
rm submissions/*.in_svm_dat
rm submissions/*.memsat_svm
rm submissions/*.out_svm_dat
rm submissions/*.pest
rm submissions/*.a3m
rm submissions/*.pbdat
rm submissions/*.sigp
rm submissions/*.new
rm submissions/*.stdout
rm submissions/*.mp_hb
rm submissions/*.mp_stage1
rm submissions/*.mp_stage2
rm submissions/*.pairstats
rm submissions/*.seqfeat
rm submissions/*.wolfpsort
rm submissions/*.netNglyc
rm submissions/*.netOglyc
rm submissions/*.dssp
rm submissions/*.dsspout
rm submissions/*.fasta
rm submissions/*.aln
rm submissions/*.ccmpred
rm submissions/*.netphos
rm submissions/*.lowc
rm submissions/*.evfold
rm submissions/*.contactnewfasta
rm submissions/*.presults
rm submissions/*.pseudo
rm submissions/*.ssf
rm submissions/*.hs-pred.out
rm submissions/*.hb2
rm submissions/*.full_*
rm submissions/*.featcfg
rm submissions/*.ali
rm submissions/*.py
rm submissions/*.align
rm submissions/*.dfout
rm submissions/*.DATA
rm submissions/*.pro
rm submissions/*.out
rm submissions/*.colstats
rm submissions/*.pdomaligns
rm submissions/*.ps
rm submissions/*.results
rm submissions/*.blastaligns
rm submissions/*.pdf
rm submissions/*.featfcfg
