#!/bin/bash
rm submissions/*.txt
rm submissions/*.png
rm submissions/*.chk
rm submissions/*.cathbls
rm submissions/*.pdbbls
rm submissions/*.pdb
rm submissions/*.nndiso
rm submissions/*.mtx
rm submissions/*.ss
rm submissions/*.ss2
rm submissions/*.psicov
rm submissions/*.solv
rm submissions/*.coils
rm submissions/*.horiz
rm submissions/*.comb
rm submissions/*.dnb
rm submissions/*.diso
rm submissions/*.in_svm_dat
rm submissions/*.memsat_svm
rm submissions/*.out_svm_dat
rm submissions/*.pest
rm submissions/*.a3m
rm submissions/*.pbdat
rm submissions/*.sigp
rm submissions/*.new
rm submissions/*.stdout
rm submissions/*.mp_hb
rm submissions/*.mp_stage1
rm submissions/*.mp_stage2
rm submissions/*.pairstats
rm submissions/*.seqfeat
rm submissions/*.wolfpsort
rm submissions/*.netNglyc
rm submissions/*.netOglyc
rm submissions/*.dssp
rm submissions/*.dsspout
rm submissions/*.fasta
rm submissions/*.aln
rm submissions/*.ann
rm submissions/*.tmpresults
rm submissions/*.mtx6
rm submissions/*.chk6
rm submissions/*.ccmpred
rm submissions/*.netphos
rm submissions/*.lowc
rm submissions/*.evfold
rm submissions/*.contactnewfasta
rm submissions/*.presults
rm submissions/*.pseudo
rm submissions/*.ssf
rm submissions/*.hs-pred.out
rm submissions/*.hb2
rm submissions/*.full_*
rm submissions/*.featcfg
rm submissions/*.ali
rm submissions/*.py
rm submissions/*.align
rm submissions/*.dfout
rm submissions/*.DATA
rm submissions/*.pro
rm submissions/*.out
rm submissions/*.colstats
rm submissions/*.pdomaligns
rm submissions/*.ps
rm submissions/*.results
rm submissions/*.blastaligns
rm submissions/*.pdf
rm submissions/*.featfcfg
rm submissions/*.bls
rm submissions/*.fa
rm submissions/*.21c
rm submissions/*.map
rm submissions/*.tdb
rm submissions/*.lst
rm submissions/*.distpred
rm submissions/*.tm_pred
rm submissions/*.stderr
rm submissions/*.out_py
rm submissions/*.tmppresults
rm submissions/*.fsa
rm submissions/*.hhr
rm submissions/*.hhaln
rm submissions/*.blastdom
rm submissions/*.boundary
rm submissions/*.domssea
rm submissions/*.pred
rm submissions/*.fix
rm submissions/*.pir
rm submissions/*.hh_pdb
rm submissions/*.Metpred
rm submissions/*.final_pdb
rm submissions/*.MetPred
rm submissions/*.out_r
rm submissions/*.predictions
rm submissions/*.con
rm submissions/*.pssm
rm submissions/*.gif
