# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0031_auto_20160517_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='validation_type',
            field=models.IntegerField(choices=[(0, 'Continue Running Tasks'), (1, 'Stop Running Tasks')], default=0),
        ),
    ]
