# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0032_task_validation_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='validation_type',
            new_name='completion_behaviour',
        ),
    ]
