# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0035_auto_20170113_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='custom_exit_behaviour',
            field=models.IntegerField(blank=True, choices=[(0, 'Continue Running Tasks'), (1, 'Stop Running Tasks (do not raise error)'), (3, 'Stop Running Tasks (raise error)')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='no_outputs_behaviour',
            field=models.IntegerField(choices=[(0, 'Continue Running Tasks'), (1, 'Stop Running Tasks (do not raise error)'), (3, 'Stop Running Tasks (raise error)')], default=3),
        ),
    ]
