# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0038_auto_20170120_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='incomplete_outputs_behaviour',
            field=models.IntegerField(choices=[(0, 'Continue Running Tasks'), (1, 'Stop Running Tasks (do not raise error)'), (3, 'Stop Running Tasks (raise error)')], default=0),
        ),
    ]
