# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0039_auto_20170126_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='incomplete_outputs_behaviour',
            field=models.IntegerField(choices=[(0, 'Continue Running Tasks'), (1, 'Stop Running Tasks (do not raise error)'), (3, 'Stop Running Tasks (raise error)')], default=3),
        ),
    ]
