# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0044_auto_20170217_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatorTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='validator',
            name='validation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics_automated.ValidatorTypes'),
        ),
    ]
