# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0046_remove_validator_re_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='backend',
            old_name='server_type',
            new_name='queue_type',
        ),
    ]
