# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0049_auto_20170301_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='queue_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues', to='analytics_automated.QueueType'),
        ),
    ]
