# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def load_queues(apps, schema_editor):
    Queues = apps.get_model("analytics_automated", "QueueType")
    local = Queues(name="R", execution_behaviour=3)
    local.save()
    local = Queues(name="Python", execution_behaviour=4)
    local.save()


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0050_auto_20170301_1539'),
    ]

    operations = [
        migrations.RunPython(load_queues)
    ]
