# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0056_batch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='analytics_automated.Submission'),
        ),
    ]
