# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0057_auto_20171114_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='submission',
        ),
        migrations.AddField(
            model_name='submission',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='analytics_automated.Batch'),
        ),
    ]
