# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-18 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0058_auto_20171115_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='hostname',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
