# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-25 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0060_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='software',
        ),
        migrations.AddField(
            model_name='configuration',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Dataset'), (0, 'Software'), (2, 'Misc.')], default=0, null=True),
        ),
    ]
