# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0034_auto_20170113_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='failure_behaviour',
        ),
        migrations.AddField(
            model_name='task',
            name='custom_exit_behaviour',
            field=models.IntegerField(blank=True, choices=[(0, 'Continue Running Tasks'), (1, 'Stop Running Tasks (do not raise error)')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='custom_exit_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='no_outputs_behaviour',
            field=models.IntegerField(choices=[(0, 'Continue Running Tasks'), (1, 'Stop Running Tasks (do not raise error)')], default=1),
        ),
    ]
