# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0040_auto_20170131_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='job',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
