# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0041_auto_20170214_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='value',
        ),
    ]
