# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0043_auto_20170215_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='spacing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='switchless',
            field=models.BooleanField(default=False),
        ),
    ]
