# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0047_auto_20170301_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True, unique=True)),
                ('execution_behaviour', models.IntegerField(choices=[(1, 'localhost'), (2, 'GridEngine'), (3, 'RServe')], default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='QueueTypes',
        ),
    ]
