# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0050_auto_20170301_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetype',
            name='execution_behaviour',
            field=models.IntegerField(choices=[(1, 'localhost'), (2, 'GridEngine'), (3, 'R'), (4, 'Python')], default=1),
        ),
    ]
