# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0052_auto_20170310_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(db_index=True, max_length=64, null=True, unique=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='analytics_automated.Submission')),
            ],
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterField(
            model_name='task',
            name='executable',
            field=models.CharField(max_length=8192),
        ),
    ]
