# Generated by Django 2.2 on 2021-07-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_automated', '0062_auto_20190410_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='type',
            field=models.IntegerField(blank=True, choices=[(2, 'Misc.'), (1, 'Dataset'), (0, 'Software')], default=0, null=True),
        ),
    ]
